# Generated by Django 3.1.5 on 2021-01-15 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('reviewed', 'Reviewed'), ('started', 'Started'), ('closed', 'Closed')], default='new', max_length=25)),
                ('summary', models.TextField()),
                ('opened_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date opened')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('owner', models.CharField(choices=[('', ''), ('randy', 'Randy'), ('casey', 'Casey'), ('pearse', 'Pearse')], default='', max_length=12)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
