# Generated by Django 3.1.5 on 2021-01-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludissues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('randy', 'Randy'), ('casey', 'Casey'), ('pearse', 'Pearse')], default='', max_length=12),
        ),
    ]
